### ISSUE TITLE
К обсуждению: App\Http\Controllers\FeedbackRestController

### ISSUE THREAD

**Issue by AndreyProkofyev** [entodima/Rarus-test-2#3]
**По коду:**
1.  Код должен соответствовать как минимум PSR-1 и PSR-2 
https://www.php-fig.org/psr/psr-1/ https://www.php-fig.org/psr/psr-2/

2.  Отсутствует PHPDoc

3.  При PHP >= 7.1, стоит использовать declare(strict_types=1)

4. Работа с глобальными массивами напрямую  ` @$email = $_POST['email'];`
Почему не используем https://laravel.com/docs/5.8/requests 
`$email = $request->input('email');`
?

5.  Оператор @ — зло. Не использовать. ` @$email = $_POST['email'];` 

6. Для того чтобы проверить email достаточно https://secure.php.net/manual/ru/function.filter-var.php .  Если используем Laravel , то почему не используем валидаторы  https://gist.github.com/kamerk22/4ffe185b2418158d1c09f6117732fc0f#file-usercontroller-php ?

7. Для того чтобы добавить значение в массив достаточно `$array[]=$value;`.  `array_push($errors,'Неправильно указан email');` избыточно.

8. Конструкции if else без фигурных скобок.

9. Избыточно начинать проверку условия с отрицания `if (!preg_match($re_email, $email))`, чтобы затем в ветке else if делать тоже самое без отрицания ` else if (preg_match($re_gmail, $email)) `

**По заданию**
Переписывать код не надо, но ответь пожалуйста:
1. почему нет генерации и обработки исключений?

2. Логирование по заданию это хорошо https://github.com/entodima/Rarus-test-2/blob/master/storage/logs/feedback.log 
Почему нет разделения уровней логирования? Например, когда ошибки заполнения формы?

3. Хорошо, что используешь миграции https://github.com/entodima/Rarus-test-2/blob/master/database/migrations/2019_07_14_095515_create_feedback_table.php

**Итого:**

1. По заданию ты все выполнил https://github.com/entodima/Rarus-test-2/issues/1#issuecomment-511229950

2. Комменты выше — прошу учесть как обратную связь по качеству кода и целесообразности использования фреймворка.

**Comment by entodima** [comment]
> Работа с глобальными массивами напрямую @$email = $_POST['email'];
Почему не используем https://laravel.com/docs/5.8/requests
$email = $request->input('email');
?

Когда делал, почему-то получал все время `[]`. Сейчас пробую - нормально работает. 
<hr>

> Если используем Laravel , то почему не используем валидаторы https://gist.github.com/kamerk22/4ffe185b2418158d1c09f6117732fc0f#file-usercontroller-php ?

Подумал, что это нужно было сделать на чистом php

<hr>

> Избыточно начинать проверку условия с отрицания if (!preg_match($re_email, $email)), чтобы затем в ветке else if делать тоже самое без отрицания else if (preg_match($re_gmail, $email))

Но я ведь проверяю разные выражения: `$re_email`, `$re_gmail`

<hr>

> Логирование по заданию это хорошо https://github.com/entodima/Rarus-test-2/blob/master/storage/logs/feedback.log
Почему нет разделения уровней логирования? Например, когда ошибки заполнения формы?

Хотел сделать, но в задании было 
> сохранять **все** заполнения формы в лог-файл

**Comment by AndreyProkofyev** [comment]
Ок. Принято
